// Code generated by "stringer -type=TCPState -linecomment"; DO NOT EDIT.

package netstat

import "strconv"

const _TCPState_name = "ESTABLISHEDSYN_SENTSYN_RECVFIN_WAIT1FIN_WAIT2TIME_WAITCLOSECLOSE_WAITLAST_ACKLISTENCLOSINGNEW_SYN_RECV"

var _TCPState_index = [...]uint8{0, 0, 11, 19, 27, 36, 45, 54, 59, 69, 77, 83, 90, 102}

func (i TCPState) String() string {
	if i < 0 || i >= TCPState(len(_TCPState_index)-1) {
		return "TCPState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TCPState_name[_TCPState_index[i]:_TCPState_index[i+1]]
}
